/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    evaluate
 * Signature: (Ljava/lang/String;)Lorg/example/PythonObj;
 */
JNIEXPORT jobject JNICALL Java_org_example_Main_evaluate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_Main
 * Method:    representation
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_Main_representation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
