/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonDict */

#ifndef _Included_org_python_integration_object_PythonDict
#define _Included_org_python_integration_object_PythonDict
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonDict
 * Method:    from
 * Signature: (Ljava/util/Map;)Lorg/python/integration/object/PythonDict;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonDict_from
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
