/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_AbstractPythonObject */

#ifndef _Included_org_python_integration_object_AbstractPythonObject
#define _Included_org_python_integration_object_AbstractPythonObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    keepAlive
 * Signature: ()Lorg/python/integration/object/IPythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_keepAlive
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    equals
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_python_integration_object_AbstractPythonObject_equals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    hashCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_python_integration_object_AbstractPythonObject_hashCode
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_python_integration_object_AbstractPythonObject_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    representation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_python_integration_object_AbstractPythonObject_representation
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;)Lorg/python/integration/object/IPythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_getAttribute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asCallable
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asCallable
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asInt
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asInt
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asFloat
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asFloat
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asBool
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asBool
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asStr
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asStr
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asList
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asList
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asDict
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asDict
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asTuple
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asTuple
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_AbstractPythonObject
 * Method:    asSet
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_AbstractPythonObject_asSet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
