/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_exception_PythonException */

#ifndef _Included_org_python_integration_exception_PythonException
#define _Included_org_python_integration_exception_PythonException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_python_integration_exception_PythonException_serialVersionUID
#define org_python_integration_exception_PythonException_serialVersionUID -3042686055658047285LL
#undef org_python_integration_exception_PythonException_serialVersionUID
#define org_python_integration_exception_PythonException_serialVersionUID -3387516993124229948LL
#undef org_python_integration_exception_PythonException_serialVersionUID
#define org_python_integration_exception_PythonException_serialVersionUID -7034897190745766939LL
/*
 * Class:     org_python_integration_exception_PythonException
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_python_integration_exception_PythonException_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
