/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonTuple */

#ifndef _Included_org_python_integration_object_PythonTuple
#define _Included_org_python_integration_object_PythonTuple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonTuple
 * Method:    from
 * Signature: (Ljava/util/List;)Lorg/python/integration/object/PythonTuple;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonTuple_from
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
