/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonFloat */

#ifndef _Included_org_python_integration_object_PythonFloat
#define _Included_org_python_integration_object_PythonFloat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonFloat
 * Method:    toJavaDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_python_integration_object_PythonFloat_toJavaDouble
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_PythonFloat
 * Method:    from
 * Signature: (D)Lorg/python/integration/object/PythonFloat;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonFloat_from
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
