/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_PythonCallable */

#ifndef _Included_org_python_integration_PythonCallable
#define _Included_org_python_integration_PythonCallable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_PythonCallable
 * Method:    call
 * Signature: ([Lorg/python/integration/IPythonObject;)Lorg/python/integration/IPythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_PythonCallable_call
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
