/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonBool */

#ifndef _Included_org_python_integration_object_PythonBool
#define _Included_org_python_integration_object_PythonBool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonBool
 * Method:    toJavaBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_python_integration_object_PythonBool_toJavaBoolean
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_PythonBool
 * Method:    from
 * Signature: (Z)Lorg/python/integration/object/PythonBool;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonBool_from
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
