/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_core_PythonScope */

#ifndef _Included_org_python_integration_core_PythonScope
#define _Included_org_python_integration_core_PythonScope
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_core_PythonScope
 * Method:    initializeScope
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_python_integration_core_PythonScope_initializeScope
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_core_PythonScope
 * Method:    finalizeScope
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_python_integration_core_PythonScope_finalizeScope
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
