/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonInt */

#ifndef _Included_org_python_integration_object_PythonInt
#define _Included_org_python_integration_object_PythonInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonInt
 * Method:    toJavaInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_python_integration_object_PythonInt_toJavaInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
