/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonList */

#ifndef _Included_org_python_integration_object_PythonList
#define _Included_org_python_integration_object_PythonList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonList
 * Method:    of
 * Signature: (Lorg/python/integration/object/IPythonObject;)Lorg/python/integration/object/PythonList;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonList_of
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_python_integration_object_PythonList
 * Method:    from
 * Signature: (Ljava/util/List;)Lorg/python/integration/object/PythonList;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonList_from
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
