/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    evaluate
 * Signature: (Ljava/lang/String;)Lorg/example/PythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_example_Main_evaluate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_Main
 * Method:    representation
 * Signature: (Lorg/example/PythonObject;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_Main_representation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_example_Main
 * Method:    getAttribute
 * Signature: (Lorg/example/PythonObject;Ljava/lang/String;)Lorg/example/PythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_example_Main_getAttribute
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_example_Main
 * Method:    callFunction
 * Signature: (Lorg/example/PythonObject;[Lorg/example/PythonObject;)Lorg/example/PythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_example_Main_callFunction
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_example_Main
 * Method:    free
 * Signature: (Lorg/example/PythonObject;)V
 */
JNIEXPORT void JNICALL Java_org_example_Main_free
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_example_Main
 * Method:    asInt
 * Signature: (Lorg/example/PythonObject;)I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_asInt
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
