/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_AbstractPythonObject */

#ifndef _Included_org_python_integration_AbstractPythonObject
#define _Included_org_python_integration_AbstractPythonObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_AbstractPythonObject
 * Method:    representation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_python_integration_AbstractPythonObject_representation
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_AbstractPythonObject
 * Method:    getAttribute
 * Signature: (Ljava/lang/String;)Lorg/python/integration/PythonBaseObject;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_AbstractPythonObject_getAttribute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_python_integration_AbstractPythonObject
 * Method:    asCallable
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_AbstractPythonObject_asCallable
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_AbstractPythonObject
 * Method:    asInt
 * Signature: ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_AbstractPythonObject_asInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
