/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_PythonInitializer */

#ifndef _Included_org_example_PythonInitializer
#define _Included_org_example_PythonInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_PythonInitializer
 * Method:    initializePy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_PythonInitializer_initializePy
  (JNIEnv *, jobject);

/*
 * Class:     org_example_PythonInitializer
 * Method:    finalizePy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_PythonInitializer_finalizePy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
