/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonInt */

#ifndef _Included_org_python_integration_object_PythonInt
#define _Included_org_python_integration_object_PythonInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonInt
 * Method:    toJavaLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_python_integration_object_PythonInt_toJavaLong
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_PythonInt
 * Method:    toJavaBigInteger
 * Signature: ()Ljava/math/BigInteger;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonInt_toJavaBigInteger
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_PythonInt
 * Method:    from
 * Signature: (J)Lorg/python/integration/object/PythonInt;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonInt_from
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
