/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonStr */

#ifndef _Included_org_python_integration_object_PythonStr
#define _Included_org_python_integration_object_PythonStr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonStr
 * Method:    toJavaString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_python_integration_object_PythonStr_toJavaString
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_object_PythonStr
 * Method:    from
 * Signature: (Ljava/lang/String;)Lorg/python/integration/object/PythonStr;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonStr_from
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
