/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonCallable */

#ifndef _Included_org_python_integration_object_PythonCallable
#define _Included_org_python_integration_object_PythonCallable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonCallable
 * Method:    call
 * Signature: ([Lorg/python/integration/object/IPythonObject;)Lorg/python/integration/object/IPythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonCallable_call
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_python_integration_object_PythonCallable
 * Method:    from
 * Signature: (Ljava/util/function/Consumer;)Lorg/python/integration/object/PythonCallable;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonCallable_from__Ljava_util_function_Consumer_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_python_integration_object_PythonCallable
 * Method:    from
 * Signature: (Ljava/util/function/Supplier;)Lorg/python/integration/object/PythonCallable;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonCallable_from__Ljava_util_function_Supplier_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_python_integration_object_PythonCallable
 * Method:    from
 * Signature: (Ljava/util/function/Function;)Lorg/python/integration/object/PythonCallable;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonCallable_from__Ljava_util_function_Function_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_python_integration_object_PythonCallable
 * Method:    from
 * Signature: (Ljava/util/function/BiFunction;)Lorg/python/integration/object/PythonCallable;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonCallable_from__Ljava_util_function_BiFunction_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_python_integration_object_PythonCallable
 * Method:    from
 * Signature: (Lorg/python/integration/object/PythonCallable/Function3;)Lorg/python/integration/object/PythonCallable;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonCallable_from__Lorg_python_integration_object_PythonCallable_00024Function3_2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
