/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_object_PythonSet */

#ifndef _Included_org_python_integration_object_PythonSet
#define _Included_org_python_integration_object_PythonSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_object_PythonSet
 * Method:    from
 * Signature: (Ljava/util/Set;)Lorg/python/integration/object/PythonSet;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_object_PythonSet_from
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
