/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_PythonSession */

#ifndef _Included_org_python_integration_PythonSession
#define _Included_org_python_integration_PythonSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_PythonSession
 * Method:    initializePy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_python_integration_PythonSession_initializePy
  (JNIEnv *, jobject);

/*
 * Class:     org_python_integration_PythonSession
 * Method:    finalizePy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_python_integration_PythonSession_finalizePy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
