/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_python_integration_PythonCore */

#ifndef _Included_org_python_integration_PythonCore
#define _Included_org_python_integration_PythonCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_python_integration_PythonCore
 * Method:    evaluate
 * Signature: (Ljava/lang/String;)Lorg/python/integration/IPythonObject;
 */
JNIEXPORT jobject JNICALL Java_org_python_integration_PythonCore_evaluate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_python_integration_PythonCore
 * Method:    free
 * Signature: (Lorg/python/integration/IPythonObject;)V
 */
JNIEXPORT void JNICALL Java_org_python_integration_PythonCore_free
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
